Repository maniyaom/Movie-Ticket-Booking, pull requests merged in 2024-10, with the labels that each got.

#35 dropdown menu improved
  src/Pages/AboutUs.js
  src/Pages/ContactUs.js
  src/components/Navbar.js
Labels: gssoc-ext, hacktoberfest-accepted, level1

#38 Added password visibility toggle feature in login and signup page
  package-lock.json
  package.json
  src/Pages/Login.js
  src/Pages/SignUp.js
  src/Pages/utils.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#30 feat : Responsive footer for various screen sizes
  src/components/Footer.css
Labels: gssoc-ext, hacktoberfest-accepted

#45 added new favicon #24
  public/favicon.ico
  public/favicon512x512.png
  public/index.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#48 #14 about us, contact us and login page responsive for small screens
  src/Pages/AboutUs.css
  src/Pages/AboutUs.js
  src/Pages/ContactUs.js
  src/Pages/Login.js
  src/Pages/style.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#65 Improve Social Media Icon Design with animation and Improve ScrollBar
  package-lock.json
  src/Pages/AboutUs.css
  src/Pages/AboutUs.js
  src/assets/icons/facebook2.png
  src/assets/icons/instagram2.png
  src/assets/icons/linkedin2.png
  src/components/Footer.css
  src/components/Footer.js
  src/index.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#60 Notification button Added
  package-lock.json
  package.json
  src/App.js
  src/Pages/Notifications.js
  src/components/Navbar.js
  src/index.js
Labels: gssoc-ext, hacktoberfest-accepted, level1

#87 firebase added
  package-lock.json
  package.json
  public/googleLogo.png
  src/Pages/SignUp.js
  src/Pages/style.css
  src/components/Navbar.css
  src/components/Navbar.js
  src/context/firebase.js
  src/index.js
Labels: gssoc-ext, hacktoberfest-accepted

#128 email format validation added
  src/Pages/Login.js
  src/Pages/SignUp.js
Labels: gssoc-ext, hacktoberfest-accepted, level1

#88 Removed .env File from Git Tracking
  .env
  .gitignore
Labels: gssoc-ext, hacktoberfest-accepted, level1

#129 Implement Making Search movie feature #84
  src/Pages/Home.js
  src/components/Search.css
  src/components/Search.js
Labels: gssoc-ext, hacktoberfest-accepted, level2

#169 Added Table of Contents
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#211 Fix #133 Added QR Generation and Verification for a Ticket
  package-lock.json
  package.json
  src/Pages/MovieTicket.js
  src/Pages/Verify.css
  src/Pages/Verify.js
  src/components/Navbar.js
  src/context/firebase.js
  src/index.js
Labels: gssoc-ext, hacktoberfest-accepted, level2

#241 Footer using TailwindCSS
  package-lock.json
  package.json
  src/components/Footer.css
  src/components/Footer.js
  tailwind.config.js
Labels: gssoc-ext, hacktoberfest-accepted, level1

#232 Added debouncing effect
  src/components/Search.js
Labels: gssoc-ext, hacktoberfest-accepted, level1

#246 dark mode support is implemented for Movie Details and Home page
  package-lock.json
  package.json
  postcss.config.js
  src/Pages/Home.css
  src/Pages/Home.js
  src/Pages/MovieDetails.js
  src/components/Navbar.js
  src/components/Search.css
  src/components/useThemeSwitcher.js
  src/index.css
  tailwind.config.js
Labels: gssoc-ext, hacktoberfest-accepted, level2

#191 underline hover effect
  src/components/Navbar.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#254 privacy-policy.js added.
  src/policies/privacy-policy.js
Labels: gssoc-ext, hacktoberfest-accepted, level1

#243 Fixes #228 Validation and Timings updated for listing a Movie
  src/Pages/AddMovie.js
  src/Pages/utils.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#286 extra margin fixed of issue #281
  package-lock.json
  src/components/Navbar.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#264 ContactUs Form added and UI enhanced
  package-lock.json
  package.json
  src/Pages/ContactUs.js
Labels: gssoc-ext, hacktoberfest-accepted

#334 Implemented Forgot Password and Signup
  src/Pages/ForgotPassword.js
  src/Pages/Login.js
  src/Pages/SignUp.js
  src/context/firebase.js
  src/index.js
Labels: gssoc-ext, hacktoberfest-accepted

#367 Multi-Lingual Support for Ticket Booking
  src/components/GoogleTranslate.jsx
  src/components/Navbar.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#424 Revert "Feedback theme changed according to the websites theme"
  package-lock.json
  package.json
  src/Pages/Feedback.js
  src/components/Navbar.js
  src/index.js
Labels: hacktoberfest-accepted
